<a href="https://colab.research.google.com/github/Dhrupad-05/Python-Libraries-for-Data-Science-For-Beginners-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 📌 README for *NumPy.ipynb*

# NumPy for Data Science — A Beginner’s Guide

This notebook introduces **NumPy (Numerical Python)** — one of the foundational Python libraries for numerical computing and data science. NumPy provides support for large, multi-dimensional arrays and matrices and a rich collection of mathematical functions to operate on them efficiently.([Wikipedia][1])

### 🚀 What You’ll Learn

* How to **import and set up NumPy**
* Create and inspect **NumPy arrays**
* Perform **basic and advanced array operations**
* Use NumPy for **vectorized math, indexing, and reshaping**
* Common NumPy **statistics and utility functions**

---

## 🛠️ Why NumPy Matters

NumPy’s `ndarray` object enables fast and efficient computation on large datasets, making it a core tool for data science, machine learning, and scientific computing in Python. Operations like broadcasting, slicing, linear algebra routines, and statistical functions are part of what makes NumPy indispensable.([dataquest.io][2])

---

## 🔍 How to Use This Notebook

1. Open the notebook in **Jupyter Notebook / JupyterLab** or **Google Colab**.
2. Run each cell sequentially to learn and experiment with NumPy features.
3. Modify examples to test array operations yourself.

---

## 🧩 Suggested Roadmap

To continue building your data science toolkit after this NumPy module:

* **pandas** — for tabular data manipulation
* **Matplotlib / Seaborn** — for data visualization
* **scikit-learn** — for machine learning models

---

## 📎 Prerequisites

Ensure you have the following installed:

```bash
pip install numpy
```

---

## 🌟 Contributions

If you want to extend this notebook with more examples (like broadcasting, random number generation, or real data usage), feel free to open a pull request!

---

## 📜 License

This project is open source — feel free to use and modify it.

---

---

## 🧠 NumPy Quick Cheatsheet for Beginners

### 📥 Import NumPy

```python
import numpy as np
```

---

### 📌 Array Creation

| Task             | Example                |
| ---------------- | ---------------------- |
| From Python list | `np.array([1, 2, 3])`  |
| Zeros array      | `np.zeros((3, 2))`     |
| Ones array       | `np.ones((2, 4))`      |
| Range array      | `np.arange(0, 10, 2)`  |
| Linearly spaced  | `np.linspace(0, 1, 5)` |

---

### 📈 Inspecting Arrays

| Property        | Command        |
| --------------- | -------------- |
| Shape           | `arr.shape`    |
| Size            | `arr.size`     |
| Dimensions      | `arr.ndim`     |
| Data type       | `arr.dtype`    |
| Convert to list | `arr.tolist()` |

---

### 🔁 Basic Operations

```python
a + b        # elementwise addition
a - b        # subtraction
a * b        # multiplication
a / b        # division
a ** 2       # square
```

---

### 🧮 Array Manipulation

| Operation   | Example                  |
| ----------- | ------------------------ |
| Reshape     | `arr.reshape(3, 2)`      |
| Transpose   | `arr.T`                  |
| Flatten     | `arr.flatten()`          |
| Concatenate | `np.concatenate([a, b])` |

---

### 🔎 Indexing & Slicing

```python
arr[0]         # first item
arr[1:4]       # slice
arr[:, 1]      # column 1 of 2D
arr[arr > 5]   # Boolean filter
```

---

### 📊 Statistics (Common)

```python
np.sum(arr)
np.mean(arr)
np.min(arr); np.max(arr)
np.std(arr); np.var(arr)
```

---

### 🎯 Random (Basics)

```python
np.random.rand(3,3)      # random [0,1)
np.random.randint(0,10,(2,3))  # integers
```

---

### ⚠️ Notes

* NumPy arrays are **homogeneous** (all elements same dtype), unlike Python lists.
* NumPy operations are **vectorized** — no explicit loops needed.

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
zeroes_array=np.zeros(3)
zeroes_array


array([0., 0., 0.])

In [ ]:
#1's
ones_arr=np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#fill with any number we want
fill=np.full((2,4),7)
fill

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

**Arrange**

In [ ]:
#Arange(start,stop,strp)
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

**Identity Matrix**

In [ ]:
identity_matrix=np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# **Array Properties & Operations**

Shape

In [ ]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.shape

(2, 3)

In [ ]:
#size
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.size

6

In [ ]:
#dimensions
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.ndim

2

In [ ]:
#datatype of element
arr=np.array([1,2,3,4,5.8,6,7,8,9])
arr.dtype

dtype('float64')

In [ ]:
#conversion in datatype
arr=np.array([1.2, 2.4,3.7])
int_arr= arr.astype(int)
int_arr
int_arr.dtype

dtype('int64')

In [ ]:
#different operations
import numpy as np
arr = np.array([10,20,30])

print(arr+5)
print(arr*2)
print(arr**2)

[15 25 35]
[20 40 60]
[100 400 900]


**Aggregation**

In [ ]:
arr= np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0


# **Indexing & Slicing**

In [ ]:
#indexing-> work with only one index/element
#slicing-> same but with multuiple elements
import numpy as np
arr= np.array([10,20,30,40,50])
arr[0]

np.int64(10)

In [ ]:
arr= np.array([10,20,30,40,50,60,70])
arr[1:5]#print elements from 1 to5
arr[:4]#begining to 4
arr[::2]#takes 2 steps

array([10, 30, 50, 70])

In [ ]:
#reverse an array
arr= np.array([10,20,30,40,50])
arr[::-1]

array([50, 40, 30, 20, 10])

**Fancy Indexing**-> Selecting multiple elements

In [ ]:
arr= np.array([10,20,30,40,5,60,70])
arr[[0,2,5]]

array([10, 30, 60])

**Filtering**

In [ ]:
arr= np.array([10,20,30,40,5,60,70])
print(arr[arr>25])

[30 40 60 70]


**Reshaping & Manupulating**




In [ ]:
arr= np.array([10,20,30,40,50,60])
reshape= arr.reshape(2,3)
reshape

array([[10, 20, 30],
       [40, 50, 60]])

**Ravel & Flatten**

In [ ]:
#.ravel()-> view
#.flatten()-> copy
arr2d= np.array([[10, 20, 30],
       [40, 50, 60]])
arr2d.ravel()

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr2d.flatten()

array([10, 20, 30, 40, 50, 60])

# **Data Manupulation**

In [ ]:
arr= np.array([10,20,30,40,5,60])
new_arr= np.insert(arr,2,100)
new_arr

array([ 10,  20, 100,  30,  40,   5,  60])

In [ ]:
arr_2d= np.array([[1,2],[3,4]])
new=np.insert(arr_2d,2,[5,6],axis=1)
new

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#append-> add elemnts at the last
arr=np.array([10, 20, 30])
new=np.append(arr, [40,50,60])
new

array([10, 20, 30, 40, 50, 60])

In [ ]:
#join two arrays
#axis 0->vertical stacking
#axis 1->horizontal stacking
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
new=np.concatenate((arr1,arr2),axis=0)
new

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr=np.array([10, 20, 30, 40, 50, 60])
new= np.delete(arr,3)
new

array([10, 20, 30, 50, 60])

In [ ]:
arr2d=np.array([[1, 2, 5],[3, 4, 6]])
new= np.delete(arr2d,0,axis=0)
new

array([[3, 4, 6]])

**Stacking &**

In [ ]:
#vertical stack
import numpy as np
arr1=np.array([1, 2, 5])
arr2=np.array([3, 4, 6])
print(np.vstack((arr1,arr2)))

[[1 2 5]
 [3 4 6]]


In [ ]:
#horizonral stack
import numpy as np
arr1=np.array([1, 2, 5])
arr2=np.array([3, 4, 6])
print(np.hstack((arr1,arr2)))

[1 2 5 3 4 6]


In [ ]:
#np.split
#np.hsplit
#np.hsplit
arr=np.array([10, 20, 30, 40, 50, 60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


# **Brodcasting & vectorization**

In [ ]:
import pandas as pd
import numpy as np
st= pd.read_csv("StudentsPerformance.csv")
sal= pd.read_csv("salaries.csv")
carmain=pd.read_csv("yt_car_main.csv")
carinfo= pd.read_csv("yt_car_info.csv")
usedprice= pd.read_csv("yt_car_used_prices.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'StudentsPerformance.csv'

In [ ]:
prices= np.array([100,200,300])
discount=15
final_prices=prices-(prices*discount/100)
final_prices

In [ ]:
prices= carmain["Retail_Price"].to_numpy()
discount=15
final_prices=prices-(prices*discount/100)
final_prices


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([5,6])
uv=arr1*2

uv

array([2, 4, 6])

In [ ]:
matrix= np.array([[1, 2, 5],[3, 4, 6]])
vector= np.array([10,20,30])
result= matrix+vector
result

array([[11, 22, 35],
       [13, 24, 36]])

In [ ]:
carmain

NameError: name 'carmain' is not defined

In [ ]:
#Vertorization
prices= carmain["Retail_Price"].to_numpy()
tax=25
total=prices+(prices+tax/100)
On_road_Price=total
carmain.insert(6,"On_road_Price",total)
carmain

NameError: name 'carmain' is not defined

In [ ]:
arr= np.array([ 10,20,30])
multiplied= arr*3
multiplied

array([30, 60, 90])

# **Handling Missing Values**

In [ ]:
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr=np.nan_to_num(arr)
cleaned_arr


array([1., 2., 0., 4., 0., 6.])

In [ ]:
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr=np.nan_to_num(arr,nan=100)#putting in 100 in place of nan
cleaned_arr


array([  1.,   2., 100.,   4., 100.,   6.])

In [ ]:
#check wheter there is infinite value
arr=np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [ ]:
arr=np.array([1,2,np.inf,4,-np.inf,6])
cleaned_arr=np.nan_to_num(arr, posinf=1000, neginf=-1000)#passing 1000 inplace of infinite values
cleaned_arr


array([    1.,     2.,  1000.,     4., -1000.,     6.])