<a href="https://colab.research.google.com/github/Dhrupad-05/Python-Libraries-for-Data-Science-For-Beginners-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
zeroes_array=np.zeros(3)
zeroes_array


array([0., 0., 0.])

In [ ]:
#1's
ones_arr=np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#fill with any number we want
fill=np.full((2,4),7)
fill

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

**Arrange**

In [ ]:
#Arange(start,stop,strp)
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

**Identity Matrix**

In [ ]:
identity_matrix=np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# **Array Properties & Operations**

Shape

In [ ]:
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.shape

(2, 3)

In [ ]:
#size
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.size

6

In [ ]:
#dimensions
arr2d=np.array([[1,2,3],
                [4,5,6]])
arr2d.ndim

2

In [ ]:
#datatype of element
arr=np.array([1,2,3,4,5.8,6,7,8,9])
arr.dtype

dtype('float64')

In [ ]:
#conversion in datatype
arr=np.array([1.2, 2.4,3.7])
int_arr= arr.astype(int)
int_arr
int_arr.dtype

dtype('int64')

In [ ]:
#different operations
import numpy as np
arr = np.array([10,20,30])

print(arr+5)
print(arr*2)
print(arr**2)

[15 25 35]
[20 40 60]
[100 400 900]


**Aggregation**

In [ ]:
arr= np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0


# **Indexing & Slicing**

In [ ]:
#indexing-> work with only one index/element
#slicing-> same but with multuiple elements
import numpy as np
arr= np.array([10,20,30,40,50])
arr[0]

np.int64(10)

In [ ]:
arr= np.array([10,20,30,40,50,60,70])
arr[1:5]#print elements from 1 to5
arr[:4]#begining to 4
arr[::2]#takes 2 steps

array([10, 30, 50, 70])

In [ ]:
#reverse an array
arr= np.array([10,20,30,40,50])
arr[::-1]

array([50, 40, 30, 20, 10])

**Fancy Indexing**-> Selecting multiple elements

In [ ]:
arr= np.array([10,20,30,40,5,60,70])
arr[[0,2,5]]

array([10, 30,  5])

**Filtering**

In [ ]:
arr= np.array([10,20,30,40,5,60,70])
print(arr[arr>25])

[30 40 60 70]


**Reshaping & Manupulating**




In [ ]:
arr= np.array([10,20,30,40,50,60])
reshape= arr.reshape(2,3)
reshape

array([[10, 20, 30],
       [40, 50, 60]])

**Ravel & Flatten**

In [ ]:
#.ravel()-> view
#.flatten()-> copy
arr2d= np.array([[10, 20, 30],
       [40, 50, 60]])
arr2d.ravel()

array([10, 20, 30, 40, 50, 60])

In [ ]:
arr2d.flatten()

array([10, 20, 30, 40, 50, 60])

# **Data Manupulation**

In [ ]:
arr= np.array([10,20,30,40,5,60])
new_arr= np.insert(arr,2,100)
new_arr

array([ 10,  20, 100,  30,  40,   5,  60])

In [ ]:
arr_2d= np.array([[1,2],[3,4]])
new=np.insert(arr_2d,2,[5,6],axis=1)
new

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#append-> add elemnts at the last
arr=np.array([10, 20, 30])
new=np.append(arr, [40,50,60])
new

array([10, 20, 30, 40, 50, 60])

In [ ]:
#join two arrays
#axis 0->vertical stacking
#axis 1->horizontal stacking
arr1= np.array([1,2,3])
arr2=np.array([4,5,6])
new=np.concatenate((arr1,arr2),axis=0)
new

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr=np.array([10, 20, 30, 40, 50, 60])
new= np.delete(arr,3)
new

array([10, 20, 30, 50, 60])

In [ ]:
arr2d=np.array([[1, 2, 5],[3, 4, 6]])
new= np.delete(arr2d,0,axis=0)
new

array([[3, 4, 6]])

**Stacking &**

In [ ]:
#vertical stack
import numpy as np
arr1=np.array([1, 2, 5])
arr2=np.array([3, 4, 6])
print(np.vstack((arr1,arr2)))

[[1 2 5]
 [3 4 6]]


In [ ]:
#horizonral stack
import numpy as np
arr1=np.array([1, 2, 5])
arr2=np.array([3, 4, 6])
print(np.hstack((arr1,arr2)))

[1 2 5 3 4 6]


In [ ]:
#np.split
#np.hsplit
#np.hsplit
arr=np.array([10, 20, 30, 40, 50, 60])
print(np.split(arr,2))

[array([10, 20, 30]), array([40, 50, 60])]


# **Brodcasting & vectorization**

In [ ]:
import pandas as pd
import numpy as np
st= pd.read_csv("StudentsPerformance.csv")
sal= pd.read_csv("salaries.csv")
carmain=pd.read_csv("yt_car_main.csv")
carinfo= pd.read_csv("yt_car_info.csv")
usedprice= pd.read_csv("yt_car_used_prices.csv")

In [ ]:
prices= np.array([100,200,300])
discount=15
final_prices=prices-(prices*discount/100)
final_prices

array([ 85., 170., 255.])

In [ ]:
prices= carmain["Retail_Price"].to_numpy()
discount=15
final_prices=prices-(prices*discount/100)
final_prices


array([205700. ,  30430. ,  32130. , ...,  45891.5,  34841.5,  34841.5])

In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([5,6])
uv=arr1*2

uv

array([2, 4, 6])

In [ ]:
matrix= np.array([[1, 2, 5],[3, 4, 6]])
vector= np.array([10,20,30])
result= matrix+vector
result

array([[11, 22, 35],
       [13, 24, 36]])

In [ ]:
carmain

index          Make   Model  Year                    Trim  Retail_Price  \
0         0  Aston Martin  DBX707  2024                    Base        242000   
1         1          Audi      A3  2024       Premium w/40 TFSI         35800   
2         2          Audi      A3  2024       Premium w/40 TFSI         37800   
3         3          Audi      A3  2024  Premium Plus w/40 TFSI         41400   
4         4          Audi      A3  2024  Premium Plus w/40 TFSI         39400   
...     ...           ...     ...   ...                     ...           ...   
1554   6410        Nissan       Z  2023             Performance         50990   
1555   6411        Nissan       Z  2023              Proto Spec         53990   
1556   6412        Nissan       Z  2023              Proto Spec         53990   
1557   6413        Nissan       Z  2023                   Sport         40990   
1558   6414        Nissan       Z  2023                   Sport         40990   

     Invoice Price Body Size Body Style  
0              NaN     Large        SUV  
1          $33,653   Compact      Sedan  
2          $35,533   Compact      Sedan  
3          $38,917   Compact      Sedan  
4          $37,037   Compact      Sedan  
...            ...       ...        ...  
1554           NaN   Compact      Coupe  
1555           NaN   Compact      Coupe  
1556           NaN   Compact      Coupe  
1557           NaN   Compact      Coupe  
1558           NaN   Compact      Coupe  

[1559 rows x 9 columns]

In [ ]:
#Vertorization
prices= carmain["Retail_Price"].to_numpy()
tax=25
total=prices+(prices+tax/100)
On_road_Price=total
carmain.insert(6,"On_road_Price",total)
carmain

index          Make   Model  Year                    Trim  Retail_Price  \
0         0  Aston Martin  DBX707  2024                    Base        242000   
1         1          Audi      A3  2024       Premium w/40 TFSI         35800   
2         2          Audi      A3  2024       Premium w/40 TFSI         37800   
3         3          Audi      A3  2024  Premium Plus w/40 TFSI         41400   
4         4          Audi      A3  2024  Premium Plus w/40 TFSI         39400   
...     ...           ...     ...   ...                     ...           ...   
1554   6410        Nissan       Z  2023             Performance         50990   
1555   6411        Nissan       Z  2023              Proto Spec         53990   
1556   6412        Nissan       Z  2023              Proto Spec         53990   
1557   6413        Nissan       Z  2023                   Sport         40990   
1558   6414        Nissan       Z  2023                   Sport         40990   

      On_road_Price Invoice Price Body Size Body Style  
0         484000.25           NaN     Large        SUV  
1          71600.25       $33,653   Compact      Sedan  
2          75600.25       $35,533   Compact      Sedan  
3          82800.25       $38,917   Compact      Sedan  
4          78800.25       $37,037   Compact      Sedan  
...             ...           ...       ...        ...  
1554      101980.25           NaN   Compact      Coupe  
1555      107980.25           NaN   Compact      Coupe  
1556      107980.25           NaN   Compact      Coupe  
1557       81980.25           NaN   Compact      Coupe  
1558       81980.25           NaN   Compact      Coupe  

[1559 rows x 10 columns]

In [ ]:
arr= np.array([ 10,20,30])
multiplied= arr*3
multiplied

array([30, 60, 90])

# **Handling Missing Values**

In [ ]:
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr=np.nan_to_num(arr)
cleaned_arr


array([1., 2., 0., 4., 0., 6.])

In [ ]:
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr=np.nan_to_num(arr,nan=100)#putting in 100 in place of nan
cleaned_arr


array([  1.,   2., 100.,   4., 100.,   6.])

In [ ]:
#check wheter there is infinite value
arr=np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [ ]:
arr=np.array([1,2,np.inf,4,-np.inf,6])
cleaned_arr=np.nan_to_num(arr, posinf=1000, neginf=-1000)#passing 1000 inplace of infinite values
cleaned_arr


array([    1.,     2.,  1000.,     4., -1000.,     6.])